
public enum State {

	DEFEATED, STANDING, JUMPING, LEFT, RIGHT, FACING_LEFT, FACING_RIGHT, UP, DOWN, LEFTWALK, RIGHTWALK, SHOOT, STILL,
	FALLING, SPAWNING, SPAWNING2, GATLING, WHEELS_LEFT, WHEELS_RIGHT, ORBS, PILLAR, WHEELS_FLIPPED, TP_TO_LEFT_SIDE,
	TP_TO_RIGHT_SIDE, CLOCKWISE, COUNTERCLOCKWISE;

}
