
public enum State {

	STANDING, JUMPING, LEFT, RIGHT, UP, DOWN, LEFTWALK, RIGHTWALK, SHOOT, STILL, FALLING, SPAWNING, SPAWNING2, GATLING,
	WHEELS_LEFT, WHEELS_RIGHT, ORBS, PILLAR, WHEELS_FLIPPED, TPLEFT, TPRIGHT, CLOCKWISE, COUNTERCLOCKWISE;

}
